### ISSUE TITLE
TypeError: expected np.ndarray (got NoneType)

### ISSUE THREAD

**Issue by BIT-LiuQingXiao** [hyf015/egocentric-gaze-prediction#24]
Thanks for your shared code!  When I followed the guidelines, I met the problem as below:
Traceback (most recent call last):
  File "gaze_full.py", line 99, in <module>
    sp.train()
  File "/home/lqx/LabCode/Gaze/SP.py", line 199, in train
    loss1 = self.trainSP()
  File "/home/lqx/LabCode/Gaze/SP.py", line 125, in trainSP
    for i, sample in tqdm(enumerate(self.STTrainLoader)):
  File "/usr/local/lib/python3.5/dist-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/lqx/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/home/lqx/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/lqx/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/lqx/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/lqx/LabCode/Gaze/data/STdatas.py", line 68, in __getitem__
    flowarr.append(torch.from_numpy(currflowx))
TypeError: expected np.ndarray (got list).
I used python 3.5, Cuda 8.0, torch 0.4, opencv 2.4.13, numpy 1.14. It seems like caused by wrong numpy

**Comment by hyf015** [comment]
Thank you for your interest in the code!
I've never met such problems and neither did other reproducers. Can you check whether the optical flow files are correct? Maybe it is a data preprocessing problem.

**Comment by BIT-LiuQingXiao** [comment]
Thanks a lot, your advice works
